# Generated by Django 5.1 on 2024-08-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0002_tipo_alter_unidad_estado_cabeceraventa_detalleventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('numeracion', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'parametros',
            },
        ),
    ]
