# Generated by Django 5.0.6 on 2024-08-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0003_parametro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ruc_dni',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
